AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.netreally.bots.quiz.Hello::handle
      Runtime: java8
      CodeUri: s3://codepipeline-us-east-1-987802409920/aws-lexbot-facebook-/MyApp/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET