AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.netreally.bots.quiz.Hello::handle
      Runtime: java8
      CodeUri: ./target/aws-lex-lambda-fbapp-1.0-SNAPSHOT.jar
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET